### ISSUE TITLE
Reporting Issues and Request for Improvements

### ISSUE THREAD

**Issue by ghost** [Ibtesam-Mahmood/poke-fusion-dex#1]
![Screenshot_20231014-113628](https://github.com/Ibtesam-Mahmood/Infinite-Fusion-Pokedex/assets/139675851/3303ae4f-ee90-4398-87ba-f83434bd34e7)

Dear Ibtesam-Mahmood,

I hope this message finds you well. I would like to bring to your attention several issues I've encountered with the "Pokemon Fusion Pokedex" repository on GitHub. 

1. The fusion section of the deployed website is currently facing multiple problems, including:
   - Images not displaying properly.
   - Responsiveness issues on mobile devices.
   - Frequent crashes.
   - Pokemon selection is not responsive on short screens, causing usability problems.

2. The Pokemon custom spirits images are not functioning, likely due to the repository from which these images were extracted being disabled. This has resulted in limited functionality for this feature.

I appreciate your hard work on the Infinite Fusion Calculator, which has been an invaluable tool. However, with the current repository changes and the removal of certain image sources, there is a need for improvements to ensure that this excellent tool remains available and functional for users.

It's also worth mentioning that many of the other existing infinite fusion calculators are not working properly and do not provide a satisfactory user experience. We currently lack proper resources in this regard, making your tool even more essential.

I kindly request your assistance in addressing these issues and consider making the necessary improvements to enhance the user experience and overall functionality of the Pokemon Fusion Pokedex.

Thank you for your attention to these matters. Your dedication to this project is greatly appreciated, and I look forward to seeing these improvements in the near future.

**Comment by Ibtesam-Mahmood** [comment]
Hi @nextvish, I am so sorry I did not know that this issue was on my project until you closed it. I will look into these issues and really appreciate your kind message.
